

# POST http://localhost:3000/insert-user
# Content-Type: application/json

# {
# 	"email": "elias@gmail.com",
# 	"password":"Tanous1258",
# 	"isAdmin": 0
# }

POST http://localhost:3000/login
Content-Type: application/json

{
	"email": "elias@gmail.com",
	"password":"Tanous1258"
}

